// lines.gen.ts — 台词/字幕表（out/vo/lines.json 生成，勿手改；*词* 品牌黄；" | " 分段：一句拆成几段先后显示，不换行）
export const CAPS: Record<string, string> = {
 "s0-1": "Welcome to YouArt. | In this episode, we'll cover the workflow basics.",
 "s0-2": "By the end, you'll have turned a logo | into a short sign-reveal video. Like this.",
 "s1-1": "Open the *Workflows* page, and click *New Workflow*.",
 "s1-2": "You get a blank canvas. | Everything you build here is a *node*.",
 "s1-3": "Click the *+* button in the left toolbar | to open the node menu.",
 "s1-4": "Nodes are grouped by media type. | Hover a group to browse it.",
 "s1-5": "Or just type to *search*. We need an Image Loader.",
 "s1-6": "Drag it onto the canvas. | This node holds an image you upload.",
 "s1-7": "Click it and pick your file. Our logo is in.",
 "s1-7b": "You can also *drag* image files | straight from Finder onto the canvas.",
 "s1-7c": "Or copy files in Finder and press *⌘V*. | Several at once is fine.",
 "s1-7d": "We don't need these here, | so select them and press *Delete*.",
 "s1-8": "Another way to add nodes: | *double-click* anywhere on the canvas.",
 "s1-9": "Search for an image model. We'll use *GPT Image 2*.",
 "s1-10": "Two ways to add a node: | the + menu, or double-click the canvas.",
 "s2-1": "Every port has a color. *Green* is text, *blue* is image, | *purple* is video, *pink* is audio.",
 "s2-2": "Drag from the blue output, | and drop it anywhere on the target node.",
 "s2-3": "YouArt picks the matching input for you. | No need to aim for the dot.",
 "s2-4": "Hover a connection and click the *✕* to remove it.",
 "s2-5": "Then connect it again, the same way.",
 "s2-6": "Write your prompt in the prompt box. | We've prepared one: a boutique storefront sign with our logo.",
 "s2-7": "Click *Run*. Generation takes a minute or two, | so we'll skip ahead.",
 "s2-8": "The result shows up right inside the node.",
 "s2-9": "Now the video. Add a *Text* node for the motion prompt.",
 "s2-10": "And a video model: *Seedance 2.5*.",
 "s2-11": "Connect the image to Seedance, | then the text to Seedance.",
 "s2-12": "Image to first frame, text to prompt. | Each one finds its matching port.",
 "s2-12b": "To cut connections, hold *Control* and drag across them.",
 "s2-12c": "Or select both source nodes: a shared output dot appears. | Drag it to Seedance, and both connect at once.",
 "s2-13": "Click *Run All* at the bottom, and skip the wait.",
 "s2-14": "There's our video, playing right in the node.",
 "s2-15": "That's a complete workflow: | reference image, image model, text prompt, video model.",
 "s3-1": "Expanded nodes take up space. | Click the *arrow* in a node's corner to collapse it.",
 "s3-2": "Or select a node and press *⌘[* to collapse it.",
 "s3-3": "*⌘]* expands it again.",
 "s3-4": "To fold everything at once, | right-click the canvas and choose *Collapse All Nodes*.",
 "s3-5": "Right-click again: *Expand All Nodes* brings them back.",
 "s3-6": "There's also *Auto-collapse*. Turn it on, | and nodes you're not working on fold themselves.",
 "s3-7": "Arrow, shortcut, or right-click menu. | All three do the same thing.",
 "s4-1": "Zoomed out, it's hard to read. | Drag a box around a few nodes to select them.",
 "s4-2": "Press *F*, and the canvas frames just those.",
 "s4-3": "For a single node, *double-click* it to focus.",
 "s4-4": "With nothing selected, use *Fit view* in the zoom menu, | bottom left, to see the whole workflow.",
 "s4-5": "So F frames whatever you've selected, | and *Fit view* brings everything back.",
 "s5-1": "Our canvas got a little messy. | Press *⌘A* to select everything.",
 "s5-2": "Then press *L*. Nodes line up automatically.",
 "s5-3": "Prefer a different direction? | Use *Auto Layout* in the selection toolbar, | horizontal or vertical.",
 "s5-4": "Connected nodes stay next to each other, | so the flow stays readable.",
 "s5-5": "Forget a shortcut? | Click the *info* button at the bottom left, | then *Keyboard shortcuts*.",
 "s5-6": "Every shortcut is listed here. | ⌘A and L to tidy up, | and this panel whenever you need a reminder.",
 "s6-1": "Everything you generate is saved in *Media Assets*, | in the left toolbar.",
 "s6-2": "Drag an asset onto the canvas, | and it becomes a new node, ready to use.",
 "s6-3": "The same library lives on the *Assets* page, | for all your projects.",
 "s7-1": "Press *⌘,* to open Settings, then choose *Preferences*.",
 "s7-2": "Pick a canvas background color.",
 "s7-3": "And a pattern: dots, grid, or none.",
 "s7-4": "Right above, you can set how downloaded files are *named*.",
 "s7-5": "Click *Edit*. The name is built from blocks.",
 "s7-5b": "Remove the *Timestamp*, | and drag *YouArt* to the front.",
 "s7-5c": "The preview updates. | Click *Done* to keep it.",
 "s7-6": "Press Esc, and your canvas is updated.",
 "s8-1": "That's all for EP1: the basics of the workflow canvas.",
 "s8-2": "Next up, EP2: generating images and video, | with parameters, credits, and troubleshooting."
};
