// ui.zh.gen.ts — 产品界面英文 → 官方中文（next-intl 文案包 out/i18n/messages-*.json 抽取；build-ui-glossary.py 生成，勿手改）。
// 只收快照/驱动里出现过的串；渲染时由 scenes/_i18n.ts 的 localizeUi 逐文本节点替换。
export const UI_ZH_EXACT: Record<string, string> = {
 "2+ nodes selected": "已选 2+ 个节点",
 "Account menu": "账户菜单",
 "Add": "添加",
 "Add Composition": "添加 Composition",
 "Add Solid": "添加色块",
 "Add Text": "添加文本",
 "Add a node": "添加节点",
 "Add block": "添加字段",
 "Add cover": "添加封面",
 "Add media": "添加媒体",
 "Add node": "添加节点",
 "Add to Chat": "添加到对话框",
 "Add to Video Editor": "添加到视频编辑器",
 "Add your first link": "添加第一个链接",
 "Add your social media profiles and websites": "添加你的社交媒体主页和网站",
 "Advanced Settings": "高级设置",
 "All": "全部",
 "All nodes collapsed": "已收起全部节点",
 "All nodes expanded": "已展开全部节点",
 "Animation": "动画",
 "Archive": "归档",
 "Assets": "素材",
 "Audio models": "音频模型",
 "Audio tools": "音频工具",
 "Audio track": "音轨",
 "Audios": "音频",
 "Auto Layout": "整理节点",
 "Auto-Layout": "自动排版",
 "Auto-collapse nodes": "节点自动收起",
 "Auto-collapse turned off": "已关闭节点自动收起",
 "Auto-collapse turned on": "已开启节点自动收起",
 "Auto-run": "自动执行",
 "Avatar": "头像",
 "Background Color": "背景颜色",
 "Background Pattern": "背景图案",
 "Balanced": "均衡",
 "Batch Run": "批量运行",
 "Billing": "账单",
 "Bio": "个人简介",
 "Branding": "品牌设计",
 "Canvas": "画布",
 "Change Angle": "改变角度",
 "Change Avatar": "更换头像",
 "Chat Panel Position": "聊天面板位置",
 "Choose which side of the workflow editor the chat panel appears on.": "选择聊天面板在工作流编辑器中显示的位置。",
 "Cinematic": "电影感",
 "Click to start editing": "点击开始编辑",
 "Close": "关闭",
 "Collapse All Nodes": "收起全部节点",
 "Collapse preview": "折叠预览",
 "Collapse sidebar": "收起节点",
 "Comments": "评论",
 "Community": "社区",
 "Community Assets": "社区素材",
 "Composition": "整体设置",
 "Connect output": "连接输出",
 "Connector": "分隔符",
 "Creator page cover": "创作者页面封面",
 "Custom": "自定义",
 "Custom connector": "自定义分隔符",
 "Cut connections": "切断连线",
 "Dark": "深色",
 "Date": "日期",
 "Default": "默认",
 "Delete": "删除",
 "Delete connection": "删除连线",
 "Describe": "反推提示",
 "Describe what you want to create...": "输入提示词，描述你想要的画面...",
 "Detailed": "精细",
 "Display Language": "显示语言",
 "Display Name": "显示名称",
 "Done": "完成",
 "Dots": "点阵",
 "Double-click": "双击",
 "Download": "下载",
 "Download All Resources": "批量下载",
 "Download Filename": "下载文件名",
 "Download History": "下载历史",
 "Drag": "拖拽",
 "Drag across visible wires": "拖过可见连线即可切断",
 "Drag any item onto the canvas to add it to your workflow.": "将条目拖拽到画布，即可作为节点添加到工作流画布中。",
 "Drop an image here, or click to upload": "将图片拖到此处，或点击上传",
 "Drop image here or click to replace": "拖放或点击此处替换图片",
 "Drop image here or click to upload": "拖放图片到此处或点击上传",
 "Duplicate": "创建副本",
 "Duplicate in place": "原地复制",
 "Duplicate without inputs": "复制（不保留输入）",
 "Duration": "视频时长",
 "E-commerce": "电商",
 "Earn Credits": "赚取额度",
 "Edit": "编辑",
 "Edit fullscreen": "全屏编辑",
 "Email": "邮箱",
 "Email cannot be changed": "邮箱地址无法更改",
 "Empty timeline": "时间轴为空",
 "End frame": "尾帧",
 "Events": "活动",
 "Expand All Nodes": "展开全部节点",
 "Expand Menu": "展开菜单",
 "Expand panel": "展开面板",
 "Expand sidebar": "展开节点",
 "Expand to fill": "铺满预览区",
 "Extract image to new node": "提取图片到新节点",
 "Extract video to new node": "提取视频到新节点",
 "Fast": "快速",
 "First frame": "首帧",
 "Fit to view": "聚焦视图",
 "Fit view": "适应视图",
 "Frame Extractor": "画面定格",
 "Frame rate": "帧率",
 "Frames": "帧",
 "Fullscreen": "全屏",
 "Generating...": "生成中...",
 "Grid": "网格",
 "Grid Split": "网格切分",
 "Grok Image": "Grok 图片",
 "Group": "编组",
 "Hand tool": "抓手工具",
 "Hold": "长按",
 "Home": "首页",
 "Horizontal": "水平排列",
 "Idle": "空闲",
 "Image": "图像",
 "Image Inpaint": "局部重绘",
 "Image Loader": "图像加载",
 "Image models": "图像模型",
 "Image preview toolbar": "图片预览工具栏",
 "Image tools": "图片工具",
 "Images": "图片",
 "Index": "生成序号",
 "Info": "帮助与信息",
 "Join Discord": "加入 Discord",
 "Keyboard shortcuts": "快捷键",
 "LLM Models": "LLM 模型",
 "LLM models": "LLM 模型",
 "Language": "语言",
 "Left": "左侧",
 "Lighter": "更浅",
 "Like": "点赞",
 "MCP Server": "MCP 服务",
 "Main navigation": "主导航",
 "Manage Plan": "套餐管理",
 "Media Assets": "媒体资产",
 "Minimap": "小地图",
 "Model": "模型",
 "More tools": "更多工具",
 "Mute": "静音",
 "My Projects": "我的项目",
 "Name": "名称",
 "New": "新",
 "New Node": "新建节点",
 "New Workflow": "新建工作流",
 "New nodes available": "有新节点",
 "No social links added yet": "暂无社交链接",
 "Node Assets": "节点资产",
 "Nodes": "节点",
 "Nodes arranged": "节点已整理",
 "None": "无",
 "On empty canvas": "在空白画布上",
 "One step per press": "每按一次一档",
 "Open Agent Chat": "打开智能体对话",
 "Open Comments Panel": "打开评论面板",
 "Open Video Editor": "打开视频编辑器",
 "Open activity": "打开活动",
 "Open node menu": "打开节点菜单",
 "OpenAI Image": "OpenAI 图像",
 "Pan": "平移",
 "Parameters": "参数面板",
 "Paste": "粘贴",
 "Play (Space)": "播放 (Space)",
 "Play video": "播放视频",
 "Preferences": "偏好设置",
 "Preview": "预览",
 "Preview Toolbars": "预览工具栏",
 "Previous 30 Days": "过去 30 天",
 "Previous 7 Days": "过去 7 天",
 "Profile": "个人资料",
 "Project ID": "项目 ID",
 "Project Settings": "项目设置",
 "Project menu": "项目菜单",
 "Project name": "项目名称",
 "Projects": "项目",
 "Prompt": "提示词",
 "Quality": "画质",
 "Qwen Image": "通义万相",
 "Real Faces Mode": "真人合规模式",
 "Redo": "重做",
 "Release Note": "更新动态",
 "Remove Background": "背景移除",
 "Render": "渲染",
 "Reset": "重置",
 "Resolution": "分辨率",
 "Resolution and aspect ratio": "分辨率与宽高比",
 "Right": "右侧",
 "Roles": "角色",
 "Run": "运行",
 "Run All": "运行全部",
 "Run Selected": "运行选中节点",
 "Run all components": "运行所有节点",
 "Run selected": "运行节点",
 "Run selected nodes": "运行已选节点",
 "Running": "运行中",
 "Save as Asset": "保存为资产",
 "Saved": "已保存",
 "Saving…": "保存中…",
 "Scroll": "滚动",
 "Search community": "搜索社区作品",
 "Search name, prompt, model": "搜索名称、提示词、模型",
 "Search nodes...": "搜索节点...",
 "Seedance 2.0 Omni Reference": "Seedance 2.0 全能参考",
 "Seedance 2.0 Video Extend": "Seedance 2.0 视频续写",
 "Seedance 2.5 Omni Reference": "Seedance 2.5 全能参考",
 "Seedance 2.5 Video Extend": "Seedance 2.5 视频续写",
 "Select": "选择",
 "Select (V)": "选择 (V)",
 "Select All": "全选",
 "Select all nodes": "全选节点",
 "Select asset": "选择素材",
 "Settings": "设置",
 "Share": "分享",
 "Show Run Button When Collapsed": "收起时显示运行按钮",
 "Show the run button on collapsed nodes": "在收起的节点上显示运行按钮",
 "Sign Out": "退出登录",
 "Social Media": "社交媒体",
 "Social links": "社交链接",
 "Sources": "参考源",
 "Split Clip at Playhead (C)": "在播放头处分割 (C)",
 "Star": "收藏",
 "Start Frame": "起始帧",
 "Start creating with AI, or double click to add node": "与AI对话开始创作, 或双击添加节点",
 "Sticky Note": "便签",
 "Stitch Videos": "视频拼接",
 "Supports JPEG, PNG, WebP (max 10MB)": "支持 JPEG、PNG、WebP (最大10MB)",
 "Switch Model": "切换模型",
 "TVC Ads": "TVC 广告",
 "Table": "表格",
 "Teams": "团队",
 "Tell us about yourself...": "介绍一下你自己...",
 "Templates": "模板",
 "Text": "文本",
 "Theme": "主题",
 "Theme Toggle (Light / Dark / System)": "主题切换（浅色 / 深色 / 跟随系统）",
 "Time": "时间",
 "Timestamp": "自定义时间",
 "Today": "今天",
 "Toggle AI assistant": "切换 AI 助手",
 "Toggle preview": "显示/隐藏预览",
 "Tools": "工具",
 "UGC Ads": "UGC 广告",
 "Undo": "撤销",
 "Ungroup": "取消编组",
 "Untitled Node": "未命名节点",
 "Untitled Project": "无标题项目",
 "Upgrade": "需要订阅",
 "Upload": "上传",
 "Upload Files": "上传文件",
 "Upscale": "高清放大",
 "Upscale Image": "高清放大",
 "User Manual": "操作指南",
 "Vertical": "垂直排列",
 "Video": "视频",
 "Video Editor": "视频编辑器",
 "Video Editor Preview": "视频编辑器预览",
 "Video editor help": "视频编辑器帮助",
 "Video models": "视频模型",
 "Video preview toolbar": "视频预览工具栏",
 "Video tools": "视频工具",
 "Videos": "视频",
 "Vidu Text to Video": "Vidu 文生视频",
 "View All": "查看全部",
 "Visual & Design": "视觉设计",
 "Watermark & Subtitle Remover": "视频水印/字幕消除",
 "When enabled, the AI agent can run workflows without asking for confirmation": "启用后，AI 代理可以无需确认直接运行工作流",
 "Workflow": "工作流",
 "Workflow Canvas": "工作流画布",
 "Write prompt...": "输入提示词...",
 "YouArt - AI Creative Agent | All in One AI Art Studio | Your Agentic creative workflow": "YouArt - AI Agent | 一体化 AI 艺术工作室 | AI 创意工作流",
 "YouArt Workflow": "YouArt 工作流",
 "YouArt | Workflow": "YouArt | 工作流",
 "Z-Image Turbo": "Z-Image 极速",
 "Zoom": "缩放",
 "Zoom in": "放大",
 "Zoom in or out": "放大或缩小",
 "Zoom out": "缩小",
 "Zoom to 100%": "缩放至 100%",
 "e.g. Blender, Photoshop (press Enter)": "例如：Blender、Photoshop（回车添加）",
 "e.g. Director, Animator (press Enter)": "例如：导演、动画师（回车添加）",
 "to the day": "精确到日",
 "to the hour": "精确到时",
 "to the minute": "精确到分",
 "to the second": "精确到秒",
 "upscale": "放大",
 "English": "简体中文",
 "JPG, PNG or WebP, up to 10MB.": "支持 JPG、PNG 或 WebP，最大 10MB。",
 "· On": "· 已开启"
};
/** 设置面板（[data-slot="dialog-content"]）内优先使用 settings.* 命名空间的译法 */
export const UI_ZH_SETTINGS: Record<string, string> = {
 "Auto-run": "自动运行",
 "Image": "图片",
 "Manage Plan": "管理套餐",
 "Reset": "恢复默认",
 "Text": "固定文字",
 "Timestamp": "时间戳"
};
/** 工作流列表页、素材库页（slot s1-workflows / m-assetspage）优先 navigation.* / projects.* / assets.* 译法 */
export const UI_ZH_PAGES: Record<string, string> = {
 "Assets": "素材库",
 "Auto-run": "自动运行",
 "Collapse sidebar": "收起侧边栏",
 "Duplicate": "复制",
 "Duration": "时长",
 "E-commerce": "电商产品",
 "Expand sidebar": "展开侧边栏",
 "Fast": "极速",
 "Image": "图片生成",
 "Info": "信息",
 "Manage Plan": "管理套餐",
 "Preview": "视频预览",
 "Remove Background": "移除背景",
 "Reset": "恢复默认",
 "Text": "固定文字",
 "Timestamp": "时间戳",
 "Upgrade": "升级",
 "Video": "视频生成"
};
/** 模板串：[正则, 替换]；$1 等为捕获组，时间单位另查 UI_ZH_UNITS */
export const UI_ZH_REGEX: Array<[string, string]> = [["^Connect input (\\d+)$", "连接输入 $1"], ["^Selected all (\\d+) nodes$", "已全选 $1 个节点"], ["^Edited (\\d+) (min|mins|hr|hrs|day|days|week|weeks|month|months) ago$", "编辑于 $1 $2前"], ["^More than (\\d+) new release notes$", "超过 $1 条新的更新动态"], ["^(\\d+) (mins?|hrs?|days?|weeks?) ago$", "$1 $2前"]];
export const UI_ZH_UNITS: Record<string, string> = {"min": "分钟", "mins": "分钟", "hr": "小时", "hrs": "小时", "day": "天", "days": "天", "week": "周", "weeks": "周", "month": "月", "months": "月"};
